server:
  port: 12000
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/sugeladi06/springcloud_config.git
# rabbitmq的配置信息；如下配置的rabbit除了IP都是默认值，
  rabbitmq:
    host: 192.168.192.129
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
management:
  endpoints:
    web:
      exposure:
# 暴露触发消息总线的地址
        include: bus-refresh