server:
  port:  ${port:10086}


spring:
  application:
    name: eureka-server # 应用名称，会在Eureka中作为服务的id标识（serviceId）
eureka:
  client:
    service-url:
# eureka服务地址；如果是集群则是其它服务器地址，后面要加/eureka
      defaultZone: ${defaultZone:http://127.0.0.1:10086/eureka}
# 是否注册自己，自身不提供服务所以不注册,默认为true
#    register-with-eureka: false
# 是否拉取服务
#    fetch-registry: false

